gg_rct_Arena1 = nil
gg_rct_Arena1EastPlayer = nil
gg_rct_Arena1WestPlayer = nil
gg_rct_Arena1EastSpawn = nil
gg_rct_Arena1WestSpawn = nil
gg_rct_Arena1Center = nil
gg_rct_Arena1WestNZone = nil
gg_rct_Arena1WestSZone = nil
gg_rct_Arena1EastSZone = nil
gg_rct_Arena1EastNZone = nil
gg_rct_Arena1Lane = nil
gg_rct_Arena1Shop = nil
gg_trg_Untitled_Trigger_001 = nil
function InitGlobals()
end

function CreateRegions()
    local we
    gg_rct_Arena1 = Rect(-4736.0, 2688.0, 128.0, 4480.0)
    gg_rct_Arena1EastPlayer = Rect(-448.0, 3264.0, 0.0, 3904.0)
    gg_rct_Arena1WestPlayer = Rect(-4608.0, 3264.0, -4096.0, 3904.0)
    gg_rct_Arena1EastSpawn = Rect(-672.0, 3392.0, -448.0, 3776.0)
    gg_rct_Arena1WestSpawn = Rect(-4096.0, 3392.0, -3840.0, 3776.0)
    gg_rct_Arena1Center = Rect(-2368.0, 3232.0, -2240.0, 3936.0)
    gg_rct_Arena1WestNZone = Rect(-4160.0, 3776.0, -3520.0, 4416.0)
    gg_rct_Arena1WestSZone = Rect(-4160.0, 2752.0, -3520.0, 3392.0)
    gg_rct_Arena1EastSZone = Rect(-1088.0, 2752.0, -448.0, 3392.0)
    gg_rct_Arena1EastNZone = Rect(-1088.0, 3776.0, -448.0, 4416.0)
    gg_rct_Arena1Lane = Rect(-4608.0, 3232.0, 0.0, 3936.0)
    gg_rct_Arena1Shop = Rect(-2432.0, 4096.0, -2176.0, 4480.0)
end

function Trig_Untitled_Trigger_001_Actions()
end

function InitTrig_Untitled_Trigger_001()
    gg_trg_Untitled_Trigger_001 = CreateTrigger()
    TriggerAddAction(gg_trg_Untitled_Trigger_001, Trig_Untitled_Trigger_001_Actions)
end

function InitCustomTriggers()
    InitTrig_Untitled_Trigger_001()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 2)
    ForcePlayerStartLocation(Player(8), 2)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(9), 3)
    ForcePlayerStartLocation(Player(9), 3)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(9), false)
    SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(10), 4)
    ForcePlayerStartLocation(Player(10), 4)
    SetPlayerColor(Player(10), ConvertPlayerColor(10))
    SetPlayerRacePreference(Player(10), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(10), false)
    SetPlayerController(Player(10), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(11), 5)
    ForcePlayerStartLocation(Player(11), 5)
    SetPlayerColor(Player(11), ConvertPlayerColor(11))
    SetPlayerRacePreference(Player(11), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(11), false)
    SetPlayerController(Player(11), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(12), 6)
    ForcePlayerStartLocation(Player(12), 6)
    SetPlayerColor(Player(12), ConvertPlayerColor(12))
    SetPlayerRacePreference(Player(12), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(12), false)
    SetPlayerController(Player(12), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(13), 7)
    ForcePlayerStartLocation(Player(13), 7)
    SetPlayerColor(Player(13), ConvertPlayerColor(13))
    SetPlayerRacePreference(Player(13), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(13), false)
    SetPlayerController(Player(13), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(14), 8)
    ForcePlayerStartLocation(Player(14), 8)
    SetPlayerColor(Player(14), ConvertPlayerColor(14))
    SetPlayerRacePreference(Player(14), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(14), false)
    SetPlayerController(Player(14), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(15), 9)
    ForcePlayerStartLocation(Player(15), 9)
    SetPlayerColor(Player(15), ConvertPlayerColor(15))
    SetPlayerRacePreference(Player(15), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(15), false)
    SetPlayerController(Player(15), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerTeam(Player(1), 0)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerTeam(Player(8), 1)
    SetPlayerTeam(Player(9), 1)
    SetPlayerTeam(Player(10), 1)
    SetPlayerTeam(Player(11), 1)
    SetPlayerTeam(Player(12), 1)
    SetPlayerTeam(Player(13), 1)
    SetPlayerTeam(Player(14), 1)
    SetPlayerTeam(Player(15), 1)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(14), true)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 1)
    SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 1)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(2, 8)
    SetStartLocPrio(2, 0, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 1, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 2, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 3, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 4, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 5, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 6, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(2, 9)
    SetEnemyStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(2, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(2, 2, 3, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(2, 3, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(2, 4, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(2, 5, 6, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(2, 6, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(2, 7, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(3, 2)
    SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(3, 2)
    SetEnemyStartLocPrio(3, 0, 0, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(3, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(4, 8)
    SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 3, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 4, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 5, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 6, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 7, 9, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(4, 1)
    SetEnemyStartLocPrio(4, 0, 1, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(5, 6)
    SetEnemyStartLocPrio(5, 0, 0, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(5, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(5, 2, 2, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(5, 3, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(5, 4, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(6, 3)
    SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(6, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(6, 2, 3, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(6, 3)
    SetEnemyStartLocPrio(6, 0, 3, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(6, 1, 4, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(6, 2, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 8)
    SetStartLocPrio(7, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 2, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(7, 3, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(7, 4, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(7, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 6, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(7, 8)
    SetEnemyStartLocPrio(7, 0, 1, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(7, 1, 2, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(7, 2, 3, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(7, 3, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(7, 4, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(7, 5, 6, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(7, 6, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(8, 8)
    SetStartLocPrio(8, 0, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(8, 1, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(8, 2, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(8, 3, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(8, 4, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(8, 5, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(8, 6, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(8, 4)
    SetEnemyStartLocPrio(8, 0, 2, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 1, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 2, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(9, 4)
    SetStartLocPrio(9, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 1, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 3, 8, MAP_LOC_PRIO_HIGH)
end

function main()
    SetCameraBounds(-5376.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -5632.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 5376.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 5120.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -5376.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 5120.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 5376.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -5632.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl", "Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("DalaranDay")
    SetAmbientNightSound("DalaranNight")
    SetMapMusic("Music", true, 0)
    CreateRegions()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("TRIGSTR_003")
    SetPlayers(10)
    SetTeams(10)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, 1408.0, 3712.0)
    DefineStartLocation(1, 1408.0, 3712.0)
    DefineStartLocation(2, 1344.0, 3072.0)
    DefineStartLocation(3, 1344.0, 3072.0)
    DefineStartLocation(4, 1344.0, 3072.0)
    DefineStartLocation(5, 1344.0, 3072.0)
    DefineStartLocation(6, 1344.0, 3072.0)
    DefineStartLocation(7, 1344.0, 3072.0)
    DefineStartLocation(8, 1344.0, 3072.0)
    DefineStartLocation(9, 1344.0, 3072.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

