declare var gg_rct_Spawn0: rect;
declare var gg_rct_Spawn1: rect;
declare var gg_rct_Check0: rect;
declare var gg_rct_Check1: rect;
declare var gg_rct_Check2: rect;
declare var gg_rct_Check3: rect;
declare var gg_rct_Check4: rect;
declare var gg_rct_Check5: rect;
declare var gg_rct_Vision: rect;
